export const CICLE_START = "CICLE_START"
export const FETCH_DATABASE_INIT = "FETCH_DATABASE_INIT"
export const FETCH_DATABASE_SUCCESS = "FETCH_DATABASE_SUCCESS"
export const FETCH_DATABASE_ERROR = "FETCH_DATABASE_ERROR"
