export const PROFILE_POPULATE_STORE = "PROFILE_POPULATE_STORE"
export const PROFILE_CHANGE_ACTIVE_SUBSECTION =
  "PROFILE_CHANGE_ACTIVE_SUBSECTION"
export const PROFILE_TRIGGER_TOAST = "PROFILE_TRIGGER_TOAST"
