export const PROFILE_TRIGGER_LOADING = "PROFILE_TRIGGER_LOADING"
export const PROFILE_POPULATE_STORE = "PROFILE_POPULATE_STORE"
export const PROFILE_FETCH_DATABASE_FAIL = "PROFILE_FETCH_DATABASE_FAIL"
export const PROFILE_CHANGE_ACTIVE_SUBSECTION =
  "PROFILE_CHANGE_ACTIVE_SUBSECTION"
