export const PROJECTS_POPULATE_STORE = "PROJECTS_POPULATE_STORE"
export const PROJECTS_CHANGE_ACTIVE_SECTION = "PROJECTS_CHANGE_ACTIVE_SECTION"
export const PROJECTS_SET_ACTIVE_POINTER = "PROJECTS_SET_ACTIVE_POINTER"
